-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.qctable
(
    "Estacion" text COLLATE pg_catalog."default" NOT NULL,
    est_id numeric,
    medicion numeric,
    medicion_interp numeric,
    lluvia_inst_corr numeric,
    error numeric,
    id serial NOT NULL,
    fecha timestamp with time zone,
    CONSTRAINT qctable_pkey PRIMARY KEY (id)
);
END;